name: URL_Shortner_FullStack
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db_url_shortener
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
  # volumes:
  #   - postgres_for_url_shortener:/var/lib/postgresql/data
  # express_app:
  #   container_name: backend_server_url_shortener
  #   build: ./BackEnd/.
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./BackEnd/.env
  #   restart: always
  #   volumes:
  #     - ./BackEnd/src:/app/src
  #     - ./BackEnd/package.json:/app/package.json
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
